### ISSUE TITLE
bug: [no name] buffers opens whenever i open curl

### ISSUE THREAD

**Issue by idelice** [oysandvik94/curl.nvim#18] opened 2024-07-04 08:13 UTC
<img width="347" alt="Screenshot 2024-07-04 at 11 11 32" src="https://github.com/oysandvik94/curl.nvim/assets/59118341/fae41269-f8a7-48c2-932b-28a488b365cc">

Is this intentional? It makes it hard to actually quit the plugin.

**Comment by oysandvik94** [comment] 2024-07-04 08:32
@idelice Do you have a session plugin installed? It's likely due to this, since the buffers are now writable instead of unwritable scratchpads.

Once the filetype thing is done you can ignore that filetype from the session plugin, but I can check if there is a native way to do this supported by all session plugins.

I guess I also can revert to using nofile buffers, and then just write automatically with an autocommand.

**Comment by idelice** [comment] 2024-07-04 08:35
I have no session plugin installed and this issue have existed since day 1 of using the plugin

**Comment by oysandvik94** [comment] 2024-07-04 08:38
@idelice How do you open neovim? "neovim ." or "neovim"?
And does this happen when you run "CurlOpen"?

**Comment by idelice** [comment] 2024-07-04 08:44
How do you open neovim? "neovim ." or "neovim"? - `nvim` **in the repo i'm in**
And does this happen when you run "CurlOpen"? - **yes**
And which version of neovim **- v0.10.0**

**Comment by oysandvik94** [comment] 2024-07-04 09:06
When running CurlOpen, it's supposed to open a new tab which contains two buffers. The first one is a named file, and the second is a nofile scratch buffer, which might have noname. This can be closed with ":tabc" or ":CurlClose".

I got this behaviour when running a config that only contained the curl.nvim plugin. In your plugin, it looks like it has opened two tabs?

Are you using a tab plugin? There might be some interaction there that I haven't tested.

**Comment by idelice** [comment] 2024-07-04 11:16
bufferline.nvim

**Comment by oysandvik94** [comment] 2024-07-04 11:57
Hmm, I couldn't quite reproduce it, but I have a branche where I think the window creation is a bit more stable. If you want to test it out, you can use the "filetype" branch:

{
	"oysandvik94/curl.nvim",
	branch = "filetype",
	dependencies = {
		"nvim-lua/plenary.nvim",
	},
	config = function()
		require("curl").setup()
	end,
}

I created a minimal config with just curl.nvim, bufferline.nvim and also diffview.nvim which opens open a similar tabthing. 

For me on that branch both curl.nvim and diffview.nvim seemed to open similarly.

**Comment by idelice** [comment] 2024-07-06 21:16
I still have the same issue
<img width="409" alt="Screenshot 2024-07-07 at 00 16 09" src="https://github.com/oysandvik94/curl.nvim/assets/59118341/e77274eb-0602-489b-bc7f-4bd1e4ce4120">

**Comment by oysandvik94** [comment] 2024-07-06 21:19
Is this the config you are using?

https://github.com/idelice/LazyVim

I might need to try and reproduce it on my end.

**Comment by idelice** [comment] 2024-07-06 21:24
Yes

**Comment by kohane27** [comment] 2024-07-07 02:38
Hello @oysandvik94 , hope you are doing well. I'm also facing this issue. Besides "No Name", syntax highlighting is not working:

![curl-shell](https://github.com/oysandvik94/curl.nvim/assets/57322459/1d902ee3-d88d-4563-b245-66aa1a5c8649)

and "No quotes needed" feature is not working:

![curl-feature-not-working](https://github.com/oysandvik94/curl.nvim/assets/57322459/bd7e1438-62f2-43f4-bacb-8f26cafdfe3c)

config:

```lua
return {
  "oysandvik94/curl.nvim",
  dependencies = { "nvim-lua/plenary.nvim" },
  config = function()
    require("curl").setup({})
  end,
}
```

After adding `branch = "filetype"`, even though "No Name" is still there, syntax highlighting is working; shellscript is not complaining and `No quotes needed` feature is working:

![curl-branch](https://github.com/oysandvik94/curl.nvim/assets/57322459/f8ef70dc-2a2c-4226-a734-0d033e3974a3)

I tried disabling [`bufferline.nvim`](https://github.com/akinsho/bufferline.nvim), [`scope.nvim`](https://github.com/tiagovla/scope.nvim) and [persisted.nvim](https://github.com/olimorris/persisted.nvim) but the "No Name" issue still persists. It's not a deal breaker and it's fine for me. I have too many plugins installed to eliminate the cause but I'm willing to help to test if you have a potential bugfix. Thank you again for this wonderful plugin:)

nvim v0.10.0 release

**Comment by oysandvik94** [comment] 2024-07-07 08:19
@kohane27 Thanks for testing and reporting the issue! I will try and reproduce it today with a different config, snd hopefully get a fix in the filetype branch.

Just so I understand, if you have the curl tab open, and run CurlClose, does a "no name" buffer remain that should not be there?

**Comment by oysandvik94** [comment] 2024-07-07 20:26
@kohane27 @idelice I think I have the "noname" buffer issue fixed now on the filetype branch. 

One thing that I'm not sure how to handle, which is mostly because I'm not used to working with buffers like LazyVim, is this:
When you open a buffer, but close the window of that buffer, it is still shown in the bufferline. I guess this is because the buffer isn't closed, just the window. 

However, when you run CurlClose, it will close the window and the buffer, so that's not an issue.
However, if you run "CurlOpen", then run "CurlOpen global", then the global buffer will replace the "working directory" on in the given window, which feels like expected behaviour. But when you run "CurlClose", only the shown buffer will close, meaning the global in this case. The "working directory" one wont be shown as a window, but will still be shown in the bufferline since the buffer is still not closed. 

One solution to this is to close the current curl buffer when using "CurlOpen" to switch to another curl file, meaning it is totally replaced. This will trigger a "do you wish to save?" if you have unsaved changes, which might be more obvious than if it comes up later when you dont expect it.

If you guys have any thoughts on this then let me know. And feel free to see if the noname buffers are gone on the filetype branch.

**Comment by idelice** [comment] 2024-07-07 20:33
It's still the same

<img width="1510" alt="Screenshot 2024-07-07 at 23 33 22" src="https://github.com/oysandvik94/curl.nvim/assets/59118341/72634be7-9729-483a-8834-323893a4429f">

**Comment by idelice** [comment] 2024-07-07 20:34
But.. when i do CurlClose it will actually close both buffers shown in the attachment.

**Comment by oysandvik94** [comment] 2024-07-07 20:36
I think the first noname buffer is the welcome screen actually. When you do "CurlOpen" I dont think it closes the greeter.

If you open a file, then do CurlOpen, then you might not get the noname file.

**Comment by idelice** [comment] 2024-07-07 20:38
> I think the first noname buffer is the welcome screen actually. When you do "CurlOpen" I dont think it closes the greeter.
> 
> If you open a file, then do CurlOpen, then you might not get the noname file.

You're correct. The no-name only appears if in starting screening

**Comment by oysandvik94** [comment] 2024-07-07 20:42
Great. Ref my earlier long comment, I think I will close curl buffers when using "CurlOpen" to open a new command buffer wile another is already open. That way CurlOpen will be sort of a unified view where you can switch which curl command file is open. And then I'll just implement autosave so users wont have to deal with the unsaved changes thing.

**Comment by oysandvik94** [comment] 2024-07-07 20:42
Note that there are some tests failing on "filetype" branch, so probably some minor bugs there that I will iron out tonight. I just wanted to check that I was on the right track.

**Comment by idelice** [comment] 2024-07-07 20:43
> Great. Ref my earlier long comment, I think I will close curl buffers when using "CurlOpen" to open a new command buffer wile another is already open. That way CurlOpen will be sort of a unified view where you can switch which curl command file is open. And then I'll just implement autosave so users wont have to deal with the unsaved changes thing.

I like the idea of auto-save!

**Comment by oysandvik94** [comment] 2024-07-07 21:50
Thank you guys so much for the patience and help in debugging, I really appreciate it! 

The filename branch now contains all of the futures I intended for the ".curl" filetype, and it also includes auto-saving. 
In addition to hopefully being more stable in opening and closing buffers, you can now also open any file with the ".curl" extension and press enter to run curl commands, even without using "CurlOpen" first. 

I need a little bit time to test the branch more, and write some documentation, so I wont merge to main just yet. But feel free to keep testing it out.

**Comment by kohane27** [comment] 2024-07-08 14:07
Hello @oysandvik94 hope you're doing well.

Thank you for getting back to us; I appreciate it:)

Current situation:

https://github.com/oysandvik94/curl.nvim/assets/57322459/03755f0e-59b4-479c-8b8c-0717a59f4b6a

It just keeps vsplit a new pane on a new request.

**Comment by oysandvik94** [comment] 2024-07-08 14:14
Oops, the split is a bug from the code I rushed just before bed last night.

**Comment by oysandvik94** [comment] 2024-07-08 16:59
@kohane27 I pushed a fix in my hotel room 10 minutes before dinner, so I hope it works now 😎

**Comment by kohane27** [comment] 2024-07-09 13:57
the vsplit bug is fixed but now the `No name` bug is back :cry:

**Comment by oysandvik94** [comment] 2024-07-09 14:03
Strange, didn't think I touched that code, and I thought I made a unit test for that bug :( Will squash it when I get some time

**Comment by oysandvik94** [comment] 2024-07-13 09:29
I couldn't reproduce it again myself, but I merged the changes to main now. So you can try and check the main branch again to check if the bug is still there. If so, I will dig in to it a bit more once I get back from vacation

**Comment by kohane27** [comment] 2024-07-24 04:15
@oysandvik94 I just installed the latest `main` branch and I'm very happy to report that everything is working! Thank you!

**Comment by oysandvik94** [comment] 2024-07-24 08:33
@kohane27 Fantastic! Thank you for helping debug and testing, and sorry that this took a while. I'll close the issue 💪🏻

**Closed** 2024-07-24 08:33 UTC
